{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dashwright.fullname" . }}-postgresql
  labels:
    app.kubernetes.io/name: {{ include "dashwright.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.external.password | quote }}
{{- end }}
